//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurResto.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OurResto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_256x256 {
            get {
                object obj = ResourceManager.GetObject("Add_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_left_256x256 {
            get {
                object obj = ResourceManager.GetObject("Arrow_left_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_right_256x256 {
            get {
                object obj = ResourceManager.GetObject("Arrow_right_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_256x256 {
            get {
                object obj = ResourceManager.GetObject("Calendar_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Credit_card_256x2561 {
            get {
                object obj = ResourceManager.GetObject("Credit_card_256x2561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete_256x256 {
            get {
                object obj = ResourceManager.GetObject("Delete_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_256x256 {
            get {
                object obj = ResourceManager.GetObject("Edit_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_menu_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_menu_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_restaurant_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_restaurant_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_serveur_80 {
            get {
                object obj = ResourceManager.GetObject("icons8_serveur_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Power_256x256 {
            get {
                object obj = ResourceManager.GetObject("Power_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer_alt_256x256 {
            get {
                object obj = ResourceManager.GetObject("Printer_alt_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sync_256x256 {
            get {
                object obj = ResourceManager.GetObject("Sync_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le menu du {0} du {1} n&apos;a pas pus être ajouté.
        /// </summary>
        internal static string TXTADDMENU {
            get {
                return ResourceManager.GetString("TXTADDMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les menus n&apos;ont pas pus être ajoutés.
        /// </summary>
        internal static string TXTADDMENUS {
            get {
                return ResourceManager.GetString("TXTADDMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment solder le compte de {0} {1} ?.
        /// </summary>
        internal static string TXTCONFIRMATIONSOLDER {
            get {
                return ResourceManager.GetString("TXTCONFIRMATIONSOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer le menu du {0} du {1} ?.
        /// </summary>
        internal static string TXTCONFIRMATIONSUPPRMENU {
            get {
                return ResourceManager.GetString("TXTCONFIRMATIONSUPPRMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer ces menus ?.
        /// </summary>
        internal static string TXTCONFIRMATIONSUPPRMENUS {
            get {
                return ResourceManager.GetString("TXTCONFIRMATIONSUPPRMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le compte du salarié {0} {1} n&apos;a pas pus être crédité.
        /// </summary>
        internal static string TXTCREDITCOMPTE {
            get {
                return ResourceManager.GetString("TXTCREDITCOMPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le menu du {0} du {1} n&apos;a pas pus être supprimé.
        /// </summary>
        internal static string TXTDELMENU {
            get {
                return ResourceManager.GetString("TXTDELMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de récuperer la liste des menus.
        /// </summary>
        internal static string TXTDLMENU {
            get {
                return ResourceManager.GetString("TXTDLMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de récuperer la liste des salariés.
        /// </summary>
        internal static string TXTDLSALARIES {
            get {
                return ResourceManager.GetString("TXTDLSALARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de récuperer les transactions.
        /// </summary>
        internal static string TXTDLTRANSAC {
            get {
                return ResourceManager.GetString("TXTDLTRANSAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La transaction n&apos;a pas été validé.
        /// </summary>
        internal static string TXTINSERTTRANSAC {
            get {
                return ResourceManager.GetString("TXTINSERTTRANSAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le montant entré n&apos;est pas valide.
        /// </summary>
        internal static string TXTMONTANTINCORRECT {
            get {
                return ResourceManager.GetString("TXTMONTANTINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un des plats entré est non valide.
        /// </summary>
        internal static string TXTPLATINVALIDE {
            get {
                return ResourceManager.GetString("TXTPLATINVALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La recherche de salariés à echoué.
        /// </summary>
        internal static string TXTRECHERCHESALARIE {
            get {
                return ResourceManager.GetString("TXTRECHERCHESALARIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez rendre {0} a {1} {2}.
        /// </summary>
        internal static string TXTRETURNMONEY {
            get {
                return ResourceManager.GetString("TXTRETURNMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le solde du salarié ne doit pas dépasser 100€ après une créditation.
        /// </summary>
        internal static string TXTSOLDE_100 {
            get {
                return ResourceManager.GetString("TXTSOLDE_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le compte du salarié n&apos;a pas pus être soldé.
        /// </summary>
        internal static string TXTSOLDERCOMPTE {
            get {
                return ResourceManager.GetString("TXTSOLDERCOMPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de récupérer les données.
        /// </summary>
        internal static string TXTUPDATEFAIL {
            get {
                return ResourceManager.GetString("TXTUPDATEFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le menu du {0} du {1} n&apos;a pas été mis a jour.
        /// </summary>
        internal static string TXTUPDATEMENU {
            get {
                return ResourceManager.GetString("TXTUPDATEMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le salarié {0} {1} n&apos;a pas été mis a jour.
        /// </summary>
        internal static string TXTUPDATESALARIE {
            get {
                return ResourceManager.GetString("TXTUPDATESALARIE", resourceCulture);
            }
        }
    }
}
