//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurResto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OurResto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_256x256 {
            get {
                object obj = ResourceManager.GetObject("Add_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_left_256x256 {
            get {
                object obj = ResourceManager.GetObject("Arrow_left_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_right_256x256 {
            get {
                object obj = ResourceManager.GetObject("Arrow_right_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_256x256 {
            get {
                object obj = ResourceManager.GetObject("Calendar_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Credit_card_256x2561 {
            get {
                object obj = ResourceManager.GetObject("Credit_card_256x2561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete_256x256 {
            get {
                object obj = ResourceManager.GetObject("Delete_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_256x256 {
            get {
                object obj = ResourceManager.GetObject("Edit_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_menu_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_menu_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_restaurant_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_restaurant_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_serveur_80 {
            get {
                object obj = ResourceManager.GetObject("icons8_serveur_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Power_256x256 {
            get {
                object obj = ResourceManager.GetObject("Power_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sync_256x256 {
            get {
                object obj = ResourceManager.GetObject("Sync_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le menu n&apos;a pas pus être ajouté&quot;.
        /// </summary>
        internal static string TXTADDMENU {
            get {
                return ResourceManager.GetString("TXTADDMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Voulez-vous vraiment solder le compte de {0} {1} ?&quot;.
        /// </summary>
        internal static string TXTCONFIRMATIONSOLDER {
            get {
                return ResourceManager.GetString("TXTCONFIRMATIONSOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Voulez-vous vraiment supprimer ce menu ?&quot;.
        /// </summary>
        internal static string TXTCONFIRMATIONSUPPRMENU {
            get {
                return ResourceManager.GetString("TXTCONFIRMATIONSUPPRMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le compte du salarié n&apos;a pas pus être crédité&quot;.
        /// </summary>
        internal static string TXTCREDITCOMPTE {
            get {
                return ResourceManager.GetString("TXTCREDITCOMPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le menu n&apos;a pas pus être supprimé&quot;.
        /// </summary>
        internal static string TXTDELMENU {
            get {
                return ResourceManager.GetString("TXTDELMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impossible de récuperer la liste des menus&quot;.
        /// </summary>
        internal static string TXTDLMENU {
            get {
                return ResourceManager.GetString("TXTDLMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impossible de récuperer la liste des salariés&quot;.
        /// </summary>
        internal static string TXTDLSALARIES {
            get {
                return ResourceManager.GetString("TXTDLSALARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impossible de récuperer les transactions&quot;.
        /// </summary>
        internal static string TXTDLTRANSAC {
            get {
                return ResourceManager.GetString("TXTDLTRANSAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La transaction n&apos;a pas été validé&quot;.
        /// </summary>
        internal static string TXTINSERTTRANSAC {
            get {
                return ResourceManager.GetString("TXTINSERTTRANSAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le montant entré n&apos;est pas valide&quot;.
        /// </summary>
        internal static string TXTMONTANTINCORRECT {
            get {
                return ResourceManager.GetString("TXTMONTANTINCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Un des plats entré est non valide&quot;.
        /// </summary>
        internal static string TXTPLATINVALIDE {
            get {
                return ResourceManager.GetString("TXTPLATINVALIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La recherche de salariés à echoué&quot;.
        /// </summary>
        internal static string TXTRECHERCHESALARIE {
            get {
                return ResourceManager.GetString("TXTRECHERCHESALARIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Vous devez rendre {0} a {1} {2}&quot;.
        /// </summary>
        internal static string TXTRETURNMONEY {
            get {
                return ResourceManager.GetString("TXTRETURNMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le solde du salarié ne doit pas dépasser 100€ après une créditation&quot;.
        /// </summary>
        internal static string TXTSOLDE_100 {
            get {
                return ResourceManager.GetString("TXTSOLDE_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le compte du salarié n&apos;a pas pus être soldé&quot;.
        /// </summary>
        internal static string TXTSOLDERCOMPTE {
            get {
                return ResourceManager.GetString("TXTSOLDERCOMPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Impossible de mettre à jour&quot;.
        /// </summary>
        internal static string TXTUPDATEFAIL {
            get {
                return ResourceManager.GetString("TXTUPDATEFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le menu n&apos;a pas été mis a jour&quot;.
        /// </summary>
        internal static string TXTUPDATEMENU {
            get {
                return ResourceManager.GetString("TXTUPDATEMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Le salarié n&apos;a pas été mis a jour&quot;.
        /// </summary>
        internal static string TXTUPDATESALARIE {
            get {
                return ResourceManager.GetString("TXTUPDATESALARIE", resourceCulture);
            }
        }
    }
}
